import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage } from "@/components/legal/legal-page";
import { siteConfig } from "@/data/site";

export const metadata: Metadata = {
  title: "Privacy Policy — LioranDB",
  description:
    "Privacy Policy explaining how LioranDB collects, protects, and handles personal data and infrastructure telemetry.",
};

export default function PrivacyPage() {
  return (
    <LegalPage
      title="Privacy Policy"
      intro="This Privacy Policy outlines how Lioran Developer Solutions (operating as LioranDB) collects, uses, protects, and discloses information when you visit liorandb.com, use our customer dashboard (app.liorandb.com), or subscribe to our managed database infrastructure."
    >
      <div className="legal-highlight">
        <p>
          <strong>Data Sovereignty Commitment:</strong> LioranDB was built with a fundamental mission: to support Indian data sovereignty and provide high-performance developer infrastructure where you maintain 100% control and ownership over your application data.
        </p>
      </div>

      <h2>1. Information We Collect</h2>
      <p>
        We collect only the minimum necessary information required to deliver high-performance database infrastructure, process subscription payments, and provide developer support:
      </p>
      <ul>
        <li>
          <strong>Account &amp; Registration Information:</strong> When you register on our dashboard (
          <Link href={siteConfig.appUrl} target="_blank">app.liorandb.com</Link>), we collect your name, email address, organization/company name, and contact details.
        </li>
        <li>
          <strong>Billing &amp; Transaction Details:</strong> When you subscribe to our managed plans (such as the Developer Starter plan at ₹5,000/mo), transaction processing is handled directly by our authorized payment gateway partner, <strong>Razorpay</strong>. We receive confirmation of payment, transaction IDs, billing address, and GSTIN (if provided). <em>We never store credit card numbers, CVVs, or net banking passwords on our servers.</em>
        </li>
        <li>
          <strong>Infrastructure &amp; Server Telemetry:</strong> To ensure high availability and monitor performance, our servers record standard operational logs, including IP addresses, browser/client types, connection timestamps, error rates, and query throughput metrics (e.g. read/write ops/sec).
        </li>
        <li>
          <strong>Support Communications:</strong> Records of communications, support tickets, and feature requests submitted via email (<Link href={`mailto:${siteConfig.supportEmail}`}>{siteConfig.supportEmail}</Link>) or Discord.
        </li>
      </ul>

      <h2>2. Your Application Data &amp; Database Content</h2>
      <p>
        <strong>You own your data completely.</strong> The documents, collections, indexes, and records stored within your managed or self-hosted LioranDB instances belong exclusively to you.
      </p>
      <ul>
        <li>We do not inspect, monetize, parse, or train machine learning models on your application documents.</li>
        <li>We do not broker or sell user databases. LioranDB provides the database storage engine and server hosting infrastructure.</li>
        <li>Automated snapshot backups generated by our system are encrypted and used solely for disaster recovery and restoring your specific instances upon request.</li>
      </ul>

      <h2>3. How We Use Collected Information</h2>
      <p>
        Information collected by LioranDB is used strictly for legitimate business and technical purposes:
      </p>
      <ul>
        <li>To provision, configure, and isolate your dedicated cloud database instances.</li>
        <li>To authenticate access to the customer dashboard (<Link href={siteConfig.appUrl} target="_blank">app.liorandb.com</Link>) and secure API keys.</li>
        <li>To process monthly recurring billing and invoice generation via Razorpay.</li>
        <li>To provide technical and founder support during our operational hours (6:00 PM – 10:00 PM IST, Monday to Friday).</li>
        <li>To detect, prevent, and remediate security vulnerabilities, DDoS attacks, or violations of our Terms of Service.</li>
        <li>To send essential administrative notifications, scheduled maintenance alerts, and service updates.</li>
      </ul>

      <h2>4. Third-Party Service Providers</h2>
      <p>
        We partner only with vetted, reputable third-party service providers who adhere to rigorous data protection standards:
      </p>
      <ul>
        <li>
          <strong>Payment Gateway (Razorpay):</strong> Razorpay Software Private Limited processes payments in compliance with RBI regulations and PCI-DSS Level 1 certification. Review{" "}
          <Link href="https://razorpay.com/privacy/" target="_blank" rel="noreferrer">Razorpay&apos;s Privacy Policy</Link>.
        </li>
        <li>
          <strong>Cloud &amp; Infrastructure Providers:</strong> Managed database instances are deployed on certified cloud datacenters (with priority given to Indian datacenter regions) with robust physical and network security.
        </li>
        <li>
          <strong>Communication &amp; Community:</strong> Discord and GitHub for community interaction, documentation, and issue tracking.
        </li>
      </ul>

      <h2>5. Data Security &amp; Encryption</h2>
      <p>
        We employ industry-standard technical and organizational security measures to protect your information:
      </p>
      <ul>
        <li>All web and dashboard traffic is encrypted in transit using modern TLS 1.3 / HTTPS encryption.</li>
        <li>Database communication supports secure encrypted transport protocols.</li>
        <li>Automated snapshot backups are stored with strict access controls and encryption at rest.</li>
        <li>Write-Ahead Logging (WAL) and crash-recovery mechanisms safeguard your transactions against sudden hardware faults.</li>
      </ul>

      <h2>6. Data Retention &amp; Deletion</h2>
      <p>
        We retain your account details and billing records for as long as your account remains active or as required by applicable Indian tax and accounting laws.
      </p>
      <p>
        Upon cancellation of your managed database service, your dedicated database instance and active data files will be decommissioned. You may request permanent deletion of your account and backup archives by contacting us at{" "}
        <Link href={`mailto:${siteConfig.supportEmail}`}>{siteConfig.supportEmail}</Link>.
      </p>

      <h2>7. Your Privacy Rights</h2>
      <p>
        Under applicable Indian data protection laws (including the Digital Personal Data Protection Act, 2023), you have the right to:
      </p>
      <ul>
        <li>Access a summary of the personal data we hold about you.</li>
        <li>Request correction of inaccurate or incomplete account details.</li>
        <li>Request deletion or erasure of your personal data, subject to statutory retention obligations.</li>
        <li>Withdraw consent for optional communications at any time.</li>
      </ul>

      <h2>8. Cookies &amp; Tracking</h2>
      <p>
        The public LioranDB website does not use invasive third-party advertising cookies or cross-site tracking pixels. The customer dashboard (<Link href={siteConfig.appUrl} target="_blank">app.liorandb.com</Link>) utilizes essential session tokens and local storage strictly to keep you authenticated and maintain your dashboard preferences.
      </p>

      <h2>9. Grievance Redressal &amp; Contact</h2>
      <p>
        For any questions, concerns, or grievances regarding this Privacy Policy or how your personal data is handled, please contact our Grievance Officer:
      </p>
      <ul>
        <li><strong>Entity:</strong> {siteConfig.legalEntity} (Lioran Group)</li>
        <li><strong>Attn:</strong> Swaraj Puppalwar (Founder &amp; CTO / Grievance Officer)</li>
        <li><strong>Support Email:</strong> <Link href={`mailto:${siteConfig.supportEmail}`}>{siteConfig.supportEmail}</Link></li>
        <li><strong>General Inquiries:</strong> <Link href={`mailto:${siteConfig.contactEmail}`}>{siteConfig.contactEmail}</Link></li>
        <li><strong>Operating Hours:</strong> 6:00 PM to 10:00 PM IST (Monday to Friday)</li>
        <li><strong>Location:</strong> Maharashtra, India</li>
      </ul>
    </LegalPage>
  );
}
